### ISSUE TITLE
Failed to run the tests

### ISSUE THREAD

**Issue by bekverdyan** [redisotschek/contributors_hunter#3]
**_Steps to reproduce_**

- Clone repo
- Run `npm install`
- Run `ng test`

_**Result**_
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'html' of undefined

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:72:44)

 FAIL  src/app/services/cart.service.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'html' of undefined

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:72:44)

 FAIL  src/app/services/organization-search.service.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'html' of undefined

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:72:44)

 FAIL  src/app/cart/cart.component.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'html' of undefined

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:72:44)

 FAIL  src/app/dashboard/dashboard.component.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'html' of undefined

      at new JSDOMEnvironment (node_modules/jest-environment-jsdom/build/index.js:72:44)

**_Environment_**
- Node version: `v14.17.6`
- npm version: `6.14.15`

**Comment by redisotschek** [comment]
Fixed, please try again
Properly configured spec.json didn’t get into VCS for some reason
